#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2006 Carlos Sobrinho

START=99

PROG=/bin/spot_inspection
NAME=spot_inspection


start()
{
	kill $(pidof spot_inspection)
	/root/spot_inspection_init.sh
}

stop()
{
	kill $(pidof spot_inspection)
}


